name:  Deploy on github 

on:
    workflow_dispatch

permissions:
    contents: read
    id-token: write
    pages: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -  name: checkout repo
               uses: actions/checkout@v4
            -  name: use nodejs
               uses: actions/setup-node@v3
               with:
                node-version: '20.x'
            -  name: install dependecy & build
               run: |
                  npm ci
                  npm run build
    
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: use nodejs
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: install dependecy and build
              run: |
                 npm ci
                 npm run build 
            - name: upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: './dist'
                name: 'github-pages'

    

